version: '3'
services:
  db:
    image: mysql:5.7.18
    ports:
      - "3306:3306"
    volumes:
      - /usr/local/docker/mysql/conf:/etc/mysql
      - /data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yy123456
    restart: always
    networks:
     default:
      aliases:
       - mysql
networks:
  default:
    external:
     name: internal
